<?php

/**
 * @file
 * Primary module hooks for os2web_meetings module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\os2web_meetings\Form\SettingsForm;

/**
 * Implements hook_form_alter().
 */
function os2web_meetings_agman_form_os2web_meetings_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['agman_meetings_import_details'] = [
    '#type' => 'details',
    '#title' => t('AGMAN Import settings'),
  ];

  $form['agman_meetings_import_details']['agman_meetings_manifest_path'] = [
    '#type' => 'textfield',
    '#title' => t('AGMAN Meetings manifests path'),
    '#description' => t('Example: public://agman'),
    '#default_value' => \Drupal::config(SettingsForm::$configName)
      ->get('agman_meetings_manifest_path'),
  ];
  $form['agman_meetings_import_details']['agman_meetings_import_closed_bpa_titles'] = [
    '#type' => 'textfield',
    '#title' => t('Bullet point attachments titles, whose will be imported in closed bullet point'),
    '#description' => t('Comma-separeted list of bullet point attachments titles, whose will be imported in closed bullet point. For example "indstilling,beslutning"'),
    '#default_value' => \Drupal::config(SettingsForm::$configName)
      ->get('agman_meetings_import_closed_bpa_titles')
  ];
  $form['agman_meetings_import_details']['agman_meetings_import_closed_bilags'] = [
    '#type' => 'checkbox',
    '#title' => t('Import closed bilags'),
    '#description' => t('This decides if closed bilags will be imported'),
    '#default_value' => \Drupal::config(SettingsForm::$configName)
      ->get('agman_meetings_import_closed_bilags')
  ];
  $form['agman_meetings_import_details']['agman_meetings_import_empty_bpa_title'] = [
    '#type' => 'textfield',
    '#title' => t('Empty attachment title'),
    '#description' => t('If attachment title is empty, this value will be used'),
    '#default_value' => \Drupal::config(SettingsForm::$configName)
      ->get('agman_meetings_import_empty_bpa_title')
  ];
}
